# Generated by Django 4.2.10 on 2024-07-24 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('numero_inmueble', models.AutoField(primary_key=True, serialize=False)),
                ('ci_propietario', models.CharField(max_length=10)),
                ('nombre_propietario', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.AutoField(primary_key=True, serialize=False)),
                ('gestion_pago', models.PositiveIntegerField()),
                ('estado_pago', models.CharField(max_length=50)),
                ('numero_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoinmuebles.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='GeoreferenciaInmueble',
            fields=[
                ('idgeoreferencia', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('altitud', models.FloatField()),
                ('numero_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoinmuebles.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='EspecificacionTecnica',
            fields=[
                ('idtecnico', models.AutoField(primary_key=True, serialize=False)),
                ('area_construccion', models.FloatField()),
                ('area_terreno', models.FloatField()),
                ('zona_clasificacion', models.CharField(max_length=1)),
                ('numero_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoinmuebles.inmueble')),
            ],
        ),
    ]
